alter table SAMPLER_ORDER_LINE add constraint FK_SAMPLER_ORDER_LINE_ORDER_ID foreign key (ORDER_ID) references SAMPLER_ORDER(ID);
alter table SAMPLER_ORDER_LINE add constraint FK_SAMPLER_ORDER_LINE_PRODUCT_ID foreign key (PRODUCT_ID) references SAMPLER_PRODUCT(ID);
create index IDX_SAMPLER_ORDER_LINE_ORDER on SAMPLER_ORDER_LINE (ORDER_ID);
create index IDX_SAMPLER_ORDER_LINE_PRODUCT on SAMPLER_ORDER_LINE (PRODUCT_ID);
