alter table SAMPLER_ORDER add constraint FK_SAMPLER_ORDER_CUSTOMER_ID foreign key (CUSTOMER_ID) references SAMPLER_CUSTOMER(ID);
create index IDX_SAMPLER_ORDER_CUSTOMER on SAMPLER_ORDER (CUSTOMER_ID);
