alter table SAMPLER_TASK add constraint FK_SAMPLER_TASK_ASSIGNEE_ID foreign key (ASSIGNEE_ID) references SAMPLER_CUSTOMER(ID);
alter table SAMPLER_TASK add constraint FK_SAMPLER_TASK_PARENT_TASK_ID foreign key (PARENT_TASK_ID) references SAMPLER_TASK(ID);
create index IDX_SAMPLER_TASK_PARENT_TASK on SAMPLER_TASK (PARENT_TASK_ID);
create index IDX_SAMPLER_TASK_ASSIGNEE on SAMPLER_TASK (ASSIGNEE_ID);
