alter table SAMPLER_INVOICE_ITEM add constraint FK_SAMPLER_INVOICE_ITEM_PRODUCT_ID foreign key (PRODUCT_ID) references SAMPLER_PRODUCT(ID);
alter table SAMPLER_INVOICE_ITEM add constraint FK_SAMPLER_INVOICE_ITEM_ORDER_ID foreign key (ORDER_ID) references SAMPLER_ORDER(ID);
create index IDX_SAMPLER_INVOICE_ITEM_ORDER on SAMPLER_INVOICE_ITEM (ORDER_ID);
create index IDX_SAMPLER_INVOICE_ITEM_PRODUCT on SAMPLER_INVOICE_ITEM (PRODUCT_ID);
