alter table SAMPLER_SEGMENT add constraint FK_SAMPLER_SEGMENT_TASK_SPAN_ID foreign key (TASK_SPAN_ID) references SAMPLER_TASK_SPAN(ID);
create index IDX_SAMPLER_SEGMENT_TASK_SPAN on SAMPLER_SEGMENT (TASK_SPAN_ID);
